fontInfo = {
    "fontFamily": "Yu Gothic UI",
}
textList = {
    "defaultFont": (fontInfo["fontFamily"], 9),
    "font2": (fontInfo["fontFamily"], 14),
    "font3": (fontInfo["fontFamily"], 15),
    "font4": (fontInfo["fontFamily"], 13),
    "font5": (fontInfo["fontFamily"], 20),
    "font6": (fontInfo["fontFamily"], 16),
    "font7": (fontInfo["fontFamily"], 11),
    "comicscript": {
        "fileType": "COMIC_SCRIPT",
        "cmdLabel": "コマンド名",
        "paramLabel": "パラメータ数",
        "posLabel": "挿入する位置",
        "paramNumLabel": "param{0}",
        "posValue": ["後", "前"],
        "imgInfo": "画像情報",
        "imgSizeInfo": "画像サイズ情報",
        "seInfo": "SE情報",
        "bgmInfo": "BGM情報",
        "noList": "(なし)",
        "pasteFront": "前",
        "pasteBack": "後",
        "pasteCancel": "Cancel",
        "headerModify": "ヘッダー情報修正",
        "headerInsert": "ヘッダー情報挿入",
        "headerImgLabel": "画像ファイル名",
        "headerImgIndex": "画像ファイル\nINDEX",
        "headerImgX": "x座標",
        "headerImgY": "y座標",
        "headerImgWidth": "横長さ",
        "headerImgHeight": "縦長さ",
        "headerSELabel": "SEファイル",
        "headerSEGroup": "グループ取得数",
        "headerBGMLabel": "BGMファイル",
        "headerBGMLoopFlag": "BGMループフラグ",
        "headerBGMStart": "BGM Start位置",
        "headerBGMLoopStart": "BGM Loop Start位置",
        "headerBGMLoopLabelInfo": ["ループしない", "ループする"],
        "treeNum": "番号",
        "treeName": "コマンド名",
        "cmdModify": "コマンド修正",
        "cmdInsert": "コマンド挿入",
        "cmdPaste": "コマンドコピー",
        "headerInfo": "ヘッダー情報",
        "selectNum": "選択した行番号：",
        "editLineLabel": "選択した行を修正する",
        "insertLineLabel": "選択した行に挿入する",
        "deleteLineLabel": "選択した行を削除する",
        "copyLineLabel": "選択した行をコピーする",
        "pasteLineLabel": "選択した行に貼り付けする",
        "headerEditLabel": "ヘッダー情報を修正する",
        "csvExtractLabel": "CSVで取り出す",
        "csvSaveLabel": "CSVで上書きする",
        "scriptLabel": "スクリプト内容",
    },
    "fvtMaker": {
        "fileType": "CSVファイル",
        "fvtNum": "FVT\n番号",
        "faceNum": "FACE\n番号",
        "faceWidth": "FACE\n横長さ",
        "faceHeight": "FACE\n縦長さ",
        "faceX": "FACE\nX座標",
        "faceY": "FACE\nY座標",
        "effect": "効果",
        "voNum": "VO\n番号",
        "text": "テキスト",
        "faceNum2": "FACE番号",
        "faceNumDesc": "FACEのイメージファイルの番号を指定する。\n0を指定すれば画像なし",
        "faceSize": "FACEサイズ",
        "faceSizeDesc": "切り取り方法は右の図を参照。\nデフォは[-1,-1,-1,-1]",
        "effectDesc": "0（普通【ゲームの速度に合わせて】）\
            \n1（揺らす【ゲームの速度に合わせて】）\
            \n2（下から出る【LSのみ使われた】）\
            \n3（画像がもっと下の位置【ゲームの速度に合わせて】）\
            \n4（揺らす）\
            \n5（画像がもっと下の位置）\
            \n6（画面の中央から現れる【LSのみ使われた】）\
            \n7（普通）",
        "voNum2": "VO番号",
        "voNumDesc": "VOの音声ファイルの番号を指定する。\n0を指定すれば音声なし",
        "textTag": "テキストの\nタグ",
        "textTagDesc": "<BR>、<PAGE>、<WAIT120>\n<FC#255016000></FC>などなど・・・",
        "csvLfLabel": "CSVの様式（CSVの1行目はヘッダー扱いになり、読み込みを省略する）",
        "howWrite": "作成方法",
    },
    "mdlBin": {
        "fileType": "MODEL_SCRIPT",
        "cmdLabel": "コマンド名",
        "paramLabel": "パラメータ数",
        "posLabel": "挿入する位置",
        "paramNumLabel": "param{0}",
        "posValue": ["後", "前"],
        "treeNum": "番号",
        "treeDelay": "delay",
        "treeName": "コマンド名",
        "treeFileFlag": "ファイルフラグ",
        "treeSection": "セクション",
        "cmdModify": "コマンド修正",
        "cmdInsert": "コマンド挿入",
        "cmdPaste": "コマンドコピー",
        "pasteFront": "前",
        "pasteBack": "後",
        "pasteCancel": "Cancel",
        "headerModify": "ヘッダー情報修正",
        "headerInsert": "ヘッダー情報挿入",
        "imgInfo": "画像情報",
        "imgSizeInfo": "画像サイズ情報",
        "smfInfo": "smf情報",
        "seInfo": "SE情報",
        "tgaInfo": "tga情報",
        "noList": "(なし)",
        "headerInfo": "ヘッダー情報",
        "headerImgLabel": "画像ファイル名",
        "else": "要素",
        "headerElse1Value": [0, 1],
        "headerImgIndex": "画像ファイル\nINDEX",
        "headerImgX": "x座標",
        "headerImgY": "y座標",
        "headerImgWidth": "横長さ",
        "headerImgHeight": "縦長さ",
        "headerSmfLabel": "smfファイル名",
        "headerSELabel": "SEファイル",
        "headerSEGroup": "グループ取得数",
        "headerTgaLabel": "TGAファイル名",
        "headerTgaB": "B",
        "headerTgaPer": "per",
        "listNumModifyLabel": "セクションの数変更",
        "listHeaderModifyLabel": "セクションの内容変更",
        "numModifyLabel": "リストの数変更",
        "selectNum": "選択した行番号：",
        "editLineLabel": "選択した行を修正する",
        "insertLineLabel": "選択した行に挿入する",
        "deleteLineLabel": "選択した行を削除する",
        "copyLineLabel": "選択した行をコピーする",
        "pasteLineLabel": "選択した行に貼り付けする",
        "headerEditLabel": "ヘッダー情報を修正する",
        "listNumModifyBtnLabel": "セクションの数を修正する",
        "listHeaderModifyBtnLabel": "セクションの内容を修正する",
        "numModifyBtnLabel": "リストの数を修正する",
        "csvExtractLabel": "CSVで取り出す",
        "csvSaveLabel": "CSVで上書きする",
        "scriptLabel": "スクリプト内容",
    },
    "mdlinfo": {
        "fileType": "MDLINFO",
        "mdlinfoLf": "モデル詳細情報",
        "selectNum": "選択した行番号：",
        "searchModel": "モデル検索：",
        "scriptLabel": "MDLINFO内容",
        "posLabel": "挿入する位置",
        "pos1": "{0}番の後",
        "pos2": "{0}番の前",
        "pos3": "最終番の後",
        "posSplit": "番の",
        "posLast": "最終",
        "pos4": "後",
        "pos5": "前",
        "pasteFront": "前",
        "pasteBack": "後",
        "pasteCancel": "Cancel",
        "treeNum": "番号",
        "treeSmf": "smf",
        "treeSmfType": "タイプ",
        "treeSmfEleNum": "smf要素数",
        "treeColorNum": "カラー数",
        "treeMesh": "mesh",
        "treeConst": "const",
        "treeEle1-3": "ele1-3",
        "treeDiff": "DIFF",
        "treeEmis": "EMIS",
        "treeNum2": "num",
        "editColorLabel": "カラー情報を修正する",
        "elementModifyLabel": "詳細要素を修正する",
        "elementInsertLabel": "詳細要素を挿入する",
        "elementDeleteLabel": "詳細要素を削除する",
        "texImageLabel": "イメージ改造",
        "detailModelLabel": "モデル要素改造",
        "detailModelInfo": "モデルの詳細情報",
        "detailModelTypeInfo": "モデルのタイプ情報",
        "imageListLabel": "イメージリスト",
        "smfTypeLabel": "タイプ",
        "detailModelMeshLabel": "Mesh No",
        "detailModelMtrlLabel": "Mtrl No",
        "detailModelEleNum": "ele{0}",
        "copyAnotherMdlinfo": "別のMDLINFOからコピー",
        "copyModelLabel": "MDLINFO情報コピー",
        "smfInfo": "smf要素情報",
        "smfName": "名称",
        "smfParam": "param",
        "smfInfoModify": "smf要素を\n修正する",
        "smfInfoInsert": "smf要素を\n挿入する",
        "smfInfoDelete": "smf要素を\n削除する",
        "smfElementModify": "smf要素修正",
        "smfElementInsert": "smf要素挿入",
        "binFileOrFlagLabel": "バイナリファイルとフラグ情報",
        "smfNameLabel": "smf名",
        "binFileLabel": "binファイル",
        "binFileFlag": "フラグ",
        "mdlDetailLabel": "選択したモデルの詳細情報",
        "mdlTypeLabel": "選択したモデルのタイプ情報",
        "mdlSmfEleLabel": "選択したモデルのsmf要素情報",
        "binFileFlagLabel": "binファイル、フラグ修正",
        "copyAnotherMdlinfoLabel": "別のMDLINFOからコピーする",
        "mdlinfoDeleteLabel": "選択したモデル情報を削除する",
        "mdlinfoCopyLabel": "選択した行をコピーする",
        "mdlinfoPasteLabel": "選択した行に貼り付けする",
        "addSmfModelLabel": "SMF情報でモデル追加",
    },
    "musicEditor": {
        "fileType": "MUSIC_DATA",
        "bsTitle": "1.07基準 BGMリスト",
        "csTitle": "1.06基準 BGMリスト",
        "rsTitle": "1.08基準 BGMリスト",
        "bgmNo": "No",
        "bgmFilename": "BGM ファイル名",
        "bgmName": "BGM名",
        "commonTitle": [
            "start",
            "loop start",
            "loop end"
        ],
        "changeBgmNum": "変えるbgm番号",
        "bgmModify": "BGM修正",
        "bgmSwap": "BGM入れ替え",
        "bgmModifyLabel": "このBGMを修正する",
        "bgmSwapLabel": "このBGMを入れ替える",
        "scriptLabel": "BGMリスト",
    },
    "orgInfoEditor": {
        "fileType": "TRAIN_DATA",
        "noUsed": "(未使用)",
        "unknown": "未詳",
        "noList": "なし",
        "notchLabel": "ノッチ",
        "perfLabel": "性能",
        "csvNotchSpeed": "speed",
        "csvNotchTlk": "tlk",
        "csvNotchSound": "sound",
        "csvNotchAdd": "add",
        "csvDaishaTitle": "台車モデル",
        "csvOrgNumTitle": "編成数",
        "csvMdlTitle": "車両モデル",
        "csvMdlIdxTitle": "車両index",
        "csvColTitle": "COLモデル",
        "csvColIdxTitle": "COL_index",
        "csvPantaTitle": "パンタモデル",
        "csvPantaIdxTitle": "パンタindex",
        "csvElseTitle": "属性index",
        "csvLensTitle": "レンズフレア",
        "csvTailTitle": "テールランプ",
        "csvModelIdx2Title": "モデルindex2",
        "colorCnt": "カラー数",
        "csvColorIdx": "カラー{0},",
        "csvModelIdx": "モデル{0},{1}\n",
        "csvColorModelIdx": "カラー{0},モデル{1}",
        "hurikoCnt": "振り子の曲げる段階",
        "hurikoRange": "振り子の曲げる角度(°)",
        "rainAdd": "雨の加速度",
        "rainBreake": "雨のブレーキ力",
        "rainHill": "雨の登り坂",
        "rainDown": "雨の下り坂",
        "trackOutPer": "脱線設定の係数",
        "trackKntPer": "カントの係数",
        "breakeOutPow": "ブレーキ時、脱線値上昇を軽減",
        "maxOutParam": "１フレームの最大脱線値",
        "hurikoCntSS": "振り子数",
        "hurikoAngleSS": "振り子角度",
        "trackCnt": "1両につく台車の数",
        "readTrackNum": "読み込む台車の数",
        "trackName": "TrackName",
        "trackMdlName": "標準軌モデル",
        "lowTrackMdlName": "狭軌モデル",
        "hurikoPow": "振り子の減算値",
        "oneWheelPow": "片輪走行の上昇率",
        "oneWheelTime": "片輪走行の継続時間",
        "oneWheelAfterTime": "片輪走行の継続時間後、落ちるまで時間",
        "trackComboList": ["標準軌", "狭軌"],
        "stage1PLabel": "1P",
        "stage2PLabel": "2P",
        "stage3PLabel": "3P",
        "stageTrackName": "台車",
        "stageNumLabel": "{0}ステージ",
        "extractCsv": "車両情報をCSVで取り出す",
        "extractText": "車両情報をテキストで取り出す",
        "saveCsv": "車両情報をCSVで上書き",
        "saveText": "車両情報をテキストで上書き",
        "trainModify": "この車両を修正する",
        "trainSave": "保存する",
        "allSave": "同じ倍率で全部修正する",
        "allSaveLabel": "全車両の性能を一括修正",
        "speedLfLabel": "速度",
        "perfLfLabel": "性能",
        "trainLfLabel": "車両",
        "orgModify": "この編成を修正する",
        "modelInfoModify": "モデル情報を修正",
        "SSTrainLfLabel": "車両",
        "SSRainLfLabel": "雨",
        "SSCarbLfLabel": "カーブ",
        "SSOtherLfLabel": "Other",
        "SSHurikoLfLabel": "振り子",
        "SSOneWheelLfLabel": "片輪走行",
        "noPerf": "ー",
        "modifyBtnLabel": "修正",
        "valueModify": "値変更",
        "defaultValueLabel": "デフォルトの値＝",
        "setDefaultBtnLabel": "車両の性能をデフォルトに戻す",
        "setDefaultLabel": "をデフォルトに戻す",
        "setDeleteLabel": "(削除)",
        "perfElement": "要素",
        "perfAllTrainLabel": "を全部",
        "perfCalcList": ["倍にする", "にする"],
        "editNotchLabel": "ノッチ情報修正",
        "editNotchList": ["４ノッチ", "５ノッチ", "１２ノッチ"],
        "calcMinSpeedLabel": "{0} -> {1}ノッチになる最低速度",
        "SSElsePerfModifyBtn": "修正する",
        "SSElsePerfModifyLabel": "{0}情報修正",
        "useThisPerfLabel": "この性能を使う",
        "fixedListNumLabel": "No.{0}",
        "fixedList2ModifyLabel": "elseの変更",
        "fixedList2NumLabel": "num",
        "fixedList2NameLabel": "name",
        "modelTrainLabel": "車両",
        "modelModelLabel": "モデル",
        "modelPantaLabel": "パンタ",
        "modelColLabel": "COL",
        "editModelLabel": "モデル情報修正",
        "lensInfoLabel": "レンズフレア情報",
        "lensCntLabel": "lens情報数",
        "lensNameLabel": "name",
        "lensF1Label": "f1",
        "lensB1Label": "b1",
        "lensEditCntLabel": "lens情報数の変更",
        "lensEditLabel": "lens情報の変更",
        "lensInfoLabelList": [
            "name1",
            "name2",
            "f1",
            "f2",
            "b1",
            "b2",
            "b3",
            "b4",
        ],
        "tailInfoLabel": "tail情報",
        "tailCntLabel": "tail情報数",
        "tailNameLabel": "name",
        "tailElseLabel": "else",
        "tailF1Label": "f1",
        "tailB1Label": "b1",
        "tailEditCntLabel": "tail情報数の変更",
        "tailEditLabel": "tail情報の変更",
        "tailSmfNameLabel": "name{0}",
        "tailSmfElseLabel": "else{0}",
        "menuComboValues": ["速度・性能情報", "数・モデル情報", "レンズフレア情報"],
        "menuComboSSValues": ["速度・性能情報", "数・その他情報"],
        "editStageLabel": "ステージ情報修正",
        "modified": "(改)",
        "dataCorrupted": "(データ破損)",
        "editStageDefaultTrain": "ステージのデフォルト車両変更",
    },
    "railEditor": {
        "fileType": "レールデータ",
        "railDataExtractExcel": "レールデータをエクセルで取り出す",
        "railDataSaveExcel": "レールデータをエクセルで上書きする",
        "initPos": "初期配置",
        "dummyPos": "ダミー配置？",
        "pracOrVsPos": "試運転、二人バトル配置",
        "lightInfo": "light情報",
        "stationInfo": "駅名標画像情報",
        "baseBinInfo": "ベースbin情報",
        "bgmNum": "BGM数",
        "modifyBtnLabel": "修正",
        "editBgmNumLabel": "BGM数変更",
        "editBgmListLabel": "BGMリスト変更",
        "noList": "(なし)",
        "modifyBgmLabel": "BGMの変更",
        "insertBgmLabel": "BGMの挿入",
        "editBgmInfoLabelList": ["ファイル名", "BGM名", "start", "loopStart"],
        "posLabel": "挿入する位置",
        "posValue": ["後", "前"],
        "railPosPlayerLabel": "player",
        "railPosRailNoLabel": "railNo",
        "railPosRailPosLabel": "railPos",
        "railPosB1Label": "b1",
        "railPosF1Label": "f1",
        "railPosPlayerNameLabel": "{0}P",
        "commonModifyLabel": "の変更",
        "commonInsertLabel": "の挿入",
        "editRailPosLabelList": ["railNo", "railPos", "b1", "f1"],
        "trainCount": "車両数",
        "editTrainCountLabel": "車両数変更",
        "stationNo": "初期駅表示No",
        "editStationNoLabel": "初期駅表示No変更",
        "editBaseBinAnimeLabel": "ベースbin ANIME",
        "animeCntLabel": "ANIME数",
        "editAnimeCntLabel": "ANIME数の変更",
        "editAnimeInfoLabel": "ANIME情報の変更",
        "editBinAnimeHeaderList": ["const1", "param1", "param2"],
        "else1Label": "else1",
        "editElse1Label": "else1の変更",
        "editElse1F1Label": "f{0}",
        "editElse1B1Label": "b{0}",
        "editValueLabel": "値",
        "stationInfoLabel": "駅名標位置情報",
        "stationInfoCntLabel": "駅名標位置数",
        "stationConst0Label": "const0",
        "stationAmbNoLabel": "AMB番号",
        "stationAmbChildNoLabel": "AMB子番号",
        "stationElementLabel": "ele",
        "stationImgNoLabel": "画像番号",
        "editStationCntLabel": "駅名標数の変更",
        "editStationInfoLabel": "駅名標情報の変更",
        "editStationInfoLabelList": ["const0", "AMB番号", "AMB子番号", "ele", "画像番号"],
        "smfInfoLabel": "smf情報",
        "selectNum": "選択した行番号：",
        "usedRail": "レール",
        "usedAmb": "AMB",
        "commonEditLineLabel": "選択した行を修正する",
        "commonInsertLineLabel": "選択した行に挿入する",
        "commonDeleteLineLabel": "選択した行を削除する",
        "commonCopyLineLabel": "選択した行をコピーする",
        "commonPasteLineLabel": "選択した行に貼り付けする",
        "editSmfElementListLabel": "選択した行のリストを修正する",
        "smfInfoNum": "番号",
        "smfInfoName": "smf名",
        "smfInfoFlag1": "フラグ1",
        "smfInfoFlag2": "フラグ2",
        "smfInfoLength": "長さ",
        "smfInfoMesh1": "Mesh表示1",
        "smfInfoMesh2": "Mesh表示2",
        "smfInfoKasenchuNo": "架線柱No",
        "smfInfoKasenNo": "架線No",
        "smfInfoElementList": "リスト数",
        "smfInfoE1": "e1",
        "modifySmfInfo": "smf修正",
        "insertSmfInfo": "smf挿入",
        "pasteSmfInfo": "smf貼り付け",
        "editSmfElementList": "リストの変更",
        "modelFlagList": [
            ["レール", "架線柱", "架線", "ボーン背景オブジェクト", "踏切音", "橋通過音", "スラブ軌道音", "雪が積もる"],
            ["ドリフト検索除外", "フラグ2", "フラグ3", "フラグ4", "片輪ドリフト時飛ぶ", "左側線路片輪ドリフト時飛ぶ", "右側線路片輪ドリフト時飛ぶ", "ドリフト時吹っ飛ぶ"],
        ],
        "setSmfSwitch": "switch設定",
        "pasteFront": "前",
        "pasteBack": "後",
        "pasteCancel": "Cancel",
        "modifySmfElementListLabel": "リスト変更",
        "insertSmfElementListLabel": "リスト挿入",
        "smfElementListLabel1": ["e1", "e2", "e3"],
        "smfElementListLabel2": ["e1", "e2"],
        "stationNameLabel": "駅名位置情報",
        "stationNameNum": "番号",
        "stationNameName": "駅名",
        "stationNameFlag": "駅フラグ",
        "stationNameRailNo": "レールNo",
        "stationNameF1": "f1",
        "stationNameF2": "f2",
        "stationNameF3": "f3",
        "stationNameE1": "e1",
        "stationNameE2": "e2",
        "stationNameE3": "e3",
        "stationNameE4": "e4",
        "stationNameF4": "f4",
        "stationNameF5": "f5",
        "stationNameF6": "f6",
        "modifyStationNameLabel": "駅名位置修正",
        "insertStationNameLabel": "駅名位置挿入",
        "pasteStationNameLabel": "駅名位置貼り付け",
        "else2InfoLabel": "else2",
        "else2CntLabel": "else2数",
        "modifyElse2CntLabel": "else2数の変更",
        "modifyElse2InfoLabel": "else2の変更",
        "editElse2LabelList": ["e1", "e2", "f1", "f2", "f3", "e3"],
        "cpuInfoLabel": "cpu情報",
        "cpuInfoNum": "番号",
        "cpuInfoRailNo": "レールNo",
        "cpuInfoConst1": "const1",
        "cpuInfoMode": "mode",
        "cpuInfoMinLen": "minLen",
        "cpuInfoMaxLen": "maxLen",
        "cpuInfoMaxSpeed": "maxSpeed",
        "cpuInfoMinSpeed": "minSpeed",
        "cpuInfoList": "list1",
        "cpuInfoDefSpeed": "defSpeed",
        "cpuInfoList2": "list2",
        "modifyCpuInfoLabel": "cpu情報修正",
        "insertCpuInfoLabel": "cpu情報挿入",
        "pasteCpuInfoLabel": "cpu情報貼り付け",
        "cpuInfoLsListLabel": "list{0}-{1}",
        "comicScriptLabel": "Comic Script",
        "modifyComicScriptLabel": "Comic Scriptの変更",
        "insertComicScriptLabel": "Comic Scriptの挿入",
        "editComicScriptLabelList": ["スクリプトNo", "イベントタイプ", "レールNo"],
        "editLsComicScriptFLabel": "f{0}",
        "dosansenInfoLabel": "土讃線情報",
        "dosansenCntLabel": "土讃線情報数",
        "dosansenStart": "始め",
        "dosansenEnd": "着地",
        "dosansenE1": "e1",
        "dosansenAnime": "anime",
        "dosansenE2": "e2",
        "dosansenF1": "f1",
        "editDosansenCntLabel": "土讃線情報数の変更",
        "editDosansenInfoLabel": "土讃線情報数の変更",
        "editDosansenLabelList": [
            "始めレールNo",
            "始めレールPos(from)",
            "始めレールPos(to)",
            "着地レールNo",
            "着地レールPos(from)",
            "着地レールPos(to)",
            "e1",
            "anime_f1",
            "anime_f2",
            "anime_f3",
            "anime_f4",
            "e2",
            "f1"
        ],
        "smfListAddList1": ["なし", "モデル設定通り"],
        "smfListAddList2": ["なし"],
        "railRailNo": "レールNo",
        "railSearchBtnLabel": "照会",
        "railCsvExtractLabel": "CSVで取り出す",
        "railCsvSaveLabel": "CSVで上書きする",
        "railCsToRs": "RS移植ファイル作成",
        "railBlockInfo": "ブロック情報",
        "railPrevRailNo": "繋げるレールNo",
        "railBlockNo": "ブロックNo",
        "railXyzInfo": "向きXYZ情報",
        "railDirX": "xの向き",
        "railDirY": "yの向き",
        "railDirZ": "zの向き",
        "railModelKasenInfo": "モデル、架線情報",
        "railModelLabel": "モデル(smf)",
        "railKasenNoLabel": "架線",
        "railKasenLabel": "架線(smf)",
        "railKasenchuLabel": "架線柱(smf)",
        "railPer": "per",
        "railLsVer0101": "VER0101情報",
        "railPrevRail2No": "繋げる\nレールNo(2)",
        "railPosXyzInfo": "XYZ情報",
        "railPosX": "xのpos",
        "railPosY": "yのpos",
        "railPosZ": "zのpos",
        "railRotXyzInfo": "XYZ_Rot情報",
        "railRotX": "xのrot",
        "railRotY": "yのrot",
        "railRotZ": "zのrot",
        "railFixAmbLabel": "固定AMB(smf)",
        "railFlagInfo": "フラグ情報",
        "railFlagInfoList": [
            [
                "踏み切り\n通過中の音",
                "複線ドリフトで\n飛ぶ",
                "手前位置に\n180度回転",
                "LAST_POS",
                "LAST01",
                "LAST00",
                "橋\n通過中の音",
                "Noドリフト"
            ],
            [
                "クラッシュ時\nカメラ位置を\n高く",
                "他のレールも\nドリフト対象",
                "長い車体は\n複線ドリフト\n以外は\n壁にぶつかる",
                "脱線しても\n速度が\n落ちにくい",
                "CPU振り子車両\n振り子のみ",
                "CPU\n片輪ドリフト\n戻し",
                "CPU\n右片輪ドリフト",
                "CPU\n左片輪ドリフト"
            ],
            [
                "片輪ドリフト時\n飛ぶ",
                "右側線路\n片輪ドリフト時\n飛ぶ",
                "左側線路\n片輪ドリフト時\n飛ぶ",
                "レール非表示",
                "左入力で\n土讃線",
                "右入力で\n土讃線",
                "右側に\nレールガード",
                "左側に\nレールガード"
            ],
            [
                "Disabled\nレール",
                "CPU\n転線",
                "L_RUN",
                "R_RUN",
                "フラグ5",
                "CPU\nドリフト\n戻し",
                "CPU\n右ドリフト",
                "CPU\n左ドリフト"
            ]
        ],
        "railOldFlag1": "踏み込めば\n即ジャンプ",
        "railOldFlag2": "ドライバー視点\nぐらぐら揺れる",
        "railOldFlag3": "トロリー線",
        "railOldFlag4": "低速軌道",
        "railRailInfo": "レール情報",
        "railRailDataCnt": "レール本数",
        "railCreateRevRail": "往復レール作成",
        "railNextRail": "次レール",
        "railPrevRail": "前レール",
        "railRevNextRail": "次レール(rev)",
        "railRevPrevRail": "前レール(rev)",
        "railCsvFileType": "レールデータCSV",
        "railCsToRsBinType": "RS移植BIN",
        "else3Label": "else3",
        "camLabel": "Cam",
        "else3Num": "番号",
        "editElse3InfoListLabel": "選択した行のリストを修正する",
        "editElse3Label": "{0}の変更",
        "insertElse3Label": "{0}の挿入",
        "pasteElse3InfoLabel": "{0}情報貼り付け",
        "editElse3LabelList": ["レールNo", "数"],
        "editElse3LsLabelList": ["f1", "f2", "f3", "数"],
        "editElse3ElementLabel": "{0}リスト情報",
        "editElse3ElementLabelList": ["タイプ", "railPos", "bin index", "anime1", "anime2"],
        "editElse3LsElementLabelList": ["f1", "f2", "f3", "f4", "b1"],
        "editElse3ElementModifyLabel": "{0}リスト情報の変更",
        "editElse3ElementInsertLabel": "{0}リスト情報の挿入",
        "else3ExtractCsvLabel": "CSVで取り出す",
        "else3LoadAndSaveCsvLabel": "CSVで上書きする",
        "else4Label": "else4",
        "else4CntLabel": "else4数",
        "editElse4CntLabel": "else4数の変更",
        "editElse4Label": "else4の変更",
        "editElse4ElementLabelList": ["railNo", "prevRail", "pos_x", "pos_y", "pos_z", "rot_x", "rot_y", "rot_z"],
        "ambAmbNo": "AMB No",
        "ambSearchBtnLabel": "照会",
        "ambCsvExtractLabel": "CSVで取り出す",
        "ambCsvSaveLabel": "CSVで上書きする",
        "ambInfoLabel": "AMB情報",
        "ambType": "タイプ",
        "ambLength": "長さ",
        "ambRailNo": "配置レールNo",
        "ambRailPos": "配置レールPos",
        "ambPosDirInfo": "BASE距離、向きXYZ情報",
        "ambBasePosX": "xの距離",
        "ambBasePosY": "yの距離",
        "ambBasePosZ": "zの距離",
        "ambBaseDirX": "xの向き",
        "ambBaseDirY": "yの向き",
        "ambBaseDirZ": "zの向き",
        "ambInfo2Label": "AMB情報2",
        "ambPriority": "優先度",
        "ambFog": "フォグ",
        "ambLsPos": "タイプ",
        "ambLsModel": "AMBモデル(smf)",
        "ambLsAnime": "ANIME番号",
        "ambModelInfo": "AMBモデル情報",
        "ambChildModelInfo": "AMB子モデル情報",
        "ambModelSmf": "モデル(smf)",
        "ambModelPosX": "xの距離",
        "ambModelPosY": "yの距離",
        "ambModelPosZ": "zの距離",
        "ambModelDirX": "xの向き",
        "ambModelDirY": "yの向き",
        "ambModelDirZ": "zの向き",
        "ambModelRotX": "x軸回転",
        "ambModelRotY": "y軸回転",
        "ambModelRotZ": "z軸回転",
        "ambModelPer": "per",
        "ambModelBsSmf": "モデル1(smf)",
        "ambModelBsDetail": "ポーン数",
        "ambCsvFileType": "AMBデータCSV",
        "railComboValue": [
            "BGM、配置情報",
            "要素1",
            "smf情報",
            "駅名位置情報",
            "要素2",
            "CPU情報",
            "Comic Script、土讃線",
            "レール情報",
            "要素3",
            "要素4",
            "AMB情報"
        ],
        "railLsComboValue": [
            "BGM、配置情報",
            "要素1",
            "smf情報",
            "駅名位置情報",
            "要素2",
            "CPU情報",
            "Comic Script、土讃線",
            "レール情報",
            "Cam",
            "要素4",
            "AMB情報"
        ],
    },
    "rsRail": {
        "1pRailPos": "1Pの先頭車の台車位置",
        "2pRailPos": "相手の先頭車の台車位置",
        "trainPosSearchBtnLabel": "追跡開始",
        "railNo": "レールNo",
        "railSearchBtnLabel": "照会",
        "railChangeBtnLabel": "変更",
        "railXyzInfo": "向きXYZ情報",
        "railDirX": "xの向き",
        "railDirY": "yの向き",
        "railDirZ": "zの向き",
        "railModelPer": "モデルのPER",
        "railPer": "per",
        "ambNo": "AMB No",
        "ambSearchBtnLabel": "照会",
        "ambChangeBtnLabel": "変更",
        "ambRecreateTime": "AMBの再描画時間（秒）",
        "ambInfoLabel": "AMB情報",
        "ambLength": "長さ",
        "ambRailNo": "配置レールNo",
        "ambRailPos": "オフセット",
        "ambPosDirInfo": "BASE距離、向きXYZ情報",
        "ambBasePosX": "xの距離",
        "ambBasePosY": "yの距離",
        "ambBasePosZ": "zの距離",
        "ambBaseDirX": "xの向き",
        "ambBaseDirY": "yの向き",
        "ambBaseDirZ": "zの向き",
        "ambModelInfo": "AMBモデル情報",
        "ambChildModelInfo": "AMB子モデル情報",
        "ambModelSmf": "モデル(smf)",
        "ambModelPosX": "xの距離",
        "ambModelPosY": "yの距離",
        "ambModelPosZ": "zの距離",
        "ambModelDirX": "xの向き",
        "ambModelDirY": "yの向き",
        "ambModelDirZ": "zの向き",
        "ambModelRotX": "x軸回転",
        "ambModelRotY": "y軸回転",
        "ambModelRotZ": "z軸回転",
        "ambModelPer": "per",
        "trainPosStopBtnLabel": "追跡終了",
        "saveBtnLabel": "保存",
        "modifyBtnLabel": "変更",
        "contents": "内容",
    },
    "smf": {
        "fileType": "SELENE MODEL",
        "fileListType": "SELENE MODELリスト",
        "smfVersion": "SMFバージョン：{0}",
        "meshNum": "メッシュの数：{0}",
        "frameNum": "フレームの数：{0}",
        "animeNum": "アニメーションの数：{0}",
        "frameNumFormat": "Frame No.{0}/{1}",
        "frameMatrixLabel": "フレーム用変換行列",
        "frameName": "フレームの名前",
        "frameMeshIndex": "所持しているメッシュのインデックス",
        "parentFrameIndex": "親のフレームのインデックス",
        "vCenterLabel": "中心座標 {0}",
        "vAxisLabel": "ローカルXYZ軸 {0}",
        "fLengthLabel": "XYZ軸の長さ {0}",
        "anisNumFormat": "Anis No.{0}/{1}",
        "anisName": "アニメーションの名前",
        "anisCount": "アニメーションのデータの数",
        "anisTime": "アニメーションの最終時間",
        "aniNumFormat": "{0}({1}/{2})",
        "anisTargetFrameIndex": "適用する対象のフレームのインデックス({0})",
        "meshNumFormat": "Mesh No.{0}/{1}",
        "meshName": "メッシュの名前",
        "meshMtrlNum": "所持しているマテリアルの数",
        "boneLocalMatrix": "ボーンのローカルオフセット行列",
        "boneFrameIndex": "骨の対象となるフレームのインデックス",
        "vPCLabel": "頂点の位置 {0}",
        "vPCColor": "頂点の色",
        "vNLabel": "頂点の法線 {0}",
        "vBLabel": "頂点の接線 {0}",
        "uvLabel": "頂点のテクスチャUV",
        "lightMapUvLabel": "頂点のライトマップ用テクスチャUV",
        "idxLabel": "頂点インデックス",
        "colStart": "面の開始位置",
        "colCount": "面の数",
        "colAttribute": "面の属性",
        "colIndexList": "面を構成する頂点のインデックス",
        "plainLabel": "面データ",
        "vxLabel": "頂点の位置",
        "vxColor": "頂点の色",
        "vxNLabel": "頂点の法線",
        "mtrlName": "マテリアル名",
        "polyStart": "ポリゴン開始位置",
        "polyCount": "ポリゴン数",
        "mtrlPStart": "頂点開始位置",
        "mtrlPCount": "頂点数",
        "texCommon": "テクスチャ名チャンク(通常)",
        "texLight": "テクスチャ名チャンク(ライトマップ)",
        "texDds": "テクスチャ名チャンク(DDS)",
        "texSpe": "テクスチャ名チャンク(スペキュラー用)",
        "texN": "テクスチャ名チャンク(法線マップ用)",
        "mtrlDraw": "マテリアルの描画属性",
        "zTest": "Zテスト",
        "zWrite": "Z書き込み",
        "alphaTest": "アルファテスト",
        "alphaBND": "アルファテスト(閾値)",
        "cull": "背面カリング",
        "lgt": "ライティング",
        "diffLabel": "拡散反射の色",
        "emisLabel": "自己発光の色",
        "speColor": "スペキュラーの色",
        "refractive": "反射率（大きいほど強い反射）",
        "roughly": "荒さ（大きいほどソフトな反射）",
        "bump": "視差マップ用の視差",
        "locationParentFrame": "移動先親フレーム",
        "treeMeshNumFormat": "(Mesh No.{0})",
        "smfFile": "ファイル",
        "xFile": "xファイル",
        "x3dFile": "x3dファイル",
        "swapFrame": "フレーム入れ替え",
        "scriptLabel": "構成",
        "createStandardLabel": "標準軌を作成する",
        "swapFrameLabel": "フレームの位置を入れ替える",
        "deleteFrameLabel": "フレームを消す",
        "extract3dLabel": "SMFを別の3dファイルで出力",
        "scanSmfImageLabel": "SMFファイルリストで イメージファイル検索",
        "copyImageLabel": "上記のパスに、イメージファイルをコピーするフォルダー指定",
        "framePosInfoLabel": "Frameの座標情報(x, y, z)",
        "frameRotInfoLabel": "Frameの回転情報(x, y, z, w)"
    },
    "ssUnity": {
        "csvNotchNum": "ノッチ数",
        "csvOrgNum": "編成数",
        "csvBodyClass": "bodyClass",
        "csvBodyModel": "bodyモデル",
        "csvPantaModel": "pantaモデル",
        "csvBodyClassIndexList": "bodyClass indexリスト",
        "csvBodyModelIndexList": "bodyモデル indexリスト",
        "csvPantaModelIndexList": "pantaモデル indexリスト",
        "headerNum": "番号",
        "headerPathId": "PathId",
        "headerName": "名前",
        "headerKind": "種類",
        "headerSize": "サイズ",
        "extractFile": "ファイルを取り出す",
        "saveFile": "ファイルを上書きする",
        "extractCsv": "CSVとして取り出す",
        "saveCsv": "CSV情報で上書きする",
        "loadSaveFileLabel": "ファイル",
        "loadSaveFileExcelLabel": "エクセルファイル",
        "selectNum": "選択した行番号：",
        "editDenFile": "denファイルを修正する",
        "editResourcesAssets": "resources.assetsを修正する",
        "extractFileLabel": "ファイルを取り出す",
        "saveFileLabel": "ファイルを上書きする",
        "saveResourcesAssets": "resources.assetsを保存する",
        "scriptLabel": "ファイル内容",
        "ssStageDataTabList": [
            "ストーリー、配置情報", "路線別画像データ", "画像設定情報",
            "駅名", "ＣＰＵ切り替え", "コミックスクリプト",
            "雨イベント", "土讃線スペシャル",
            "モデル情報", "レール情報", "Pri情報", "AMB情報",
        ],
        "searchText": "検索"
    },
    "infoList": {
        "I1": "このまま修正してもよろしいですか？",
        "I2": "このまま挿入してもよろしいですか？",
        "I3": "スクリプトを改造しました",
        "I4": "挿入する位置を選んでください",
        "I5": "貼り付けしました",
        "I6": "の{0}番目を削除します。\nそれでもよろしいですか？",
        "I7": "変更を保存しますか？",
        "I8": "ヘッダー情報を改造しました",
        "I9": "選択した行を削除します。\nそれでもよろしいですか？",
        "I10": "CSVで取り出しました",
        "I11": "選択したCSVで上書きします。\nそれでもよろしいですか？",
        "I12": "コピーしました",
        "I13": "変換準備ができました。\n既存のファイルは上書きされます。\nそれでもよろしいですか？",
        "I14": "全てのリストを書込みしました",
        "I15": "{0}行のデータを読み込みしました。\n上書きしますか？",
        "I16": "CSVで上書きしました",
        "I17": "※上記のparamは文字として保存されます\n\n",
        "I18": "セクション{0}の数を",
        "I19": "に修正する",
        "I20": "設定した値は現在より少なく設定してます\n",
        "I21": "この値で修正しますか？",
        "I22": "セクションの数を改造しました",
        "I23": "リストの数を改造しました",
        "I24": "リストの数を",
        "I25": "{0}番目を削除します。\nそれでもよろしいですか？",
        "I26": "モデル要素情報を修正しました",
        "I27": "入力してください",
        "I28": "イメージ情報を修正しますか？",
        "I29": "イメージ情報を修正しました",
        "I30": "【注意！】重複する要素({0}-{1})があります\n",
        "I31": "モデル要素情報を修正しますか？",
        "I32": "モデル要素情報を挿入しますか？",
        "I33": "smf要素情報を修正しました",
        "I34": "smf要素情報を修正しますか？",
        "I35": "binファイル、フラグ情報を修正しますか？",
        "I36": "binファイル、フラグ情報を修正しました",
        "I37": "コピーする要素を選んでください。\nコピーした要素は最終番に追加されます",
        "I38": "{0}をコピーしますか？",
        "I39": "このまま入れ替えてもよろしいですか？",
        "I40": "{0}番と{1}番を入れ替えます。\n",
        "I41": "BGMを修正しました",
        "I42": "ステージ情報を修正しますか？",
        "I43": "ステージ設定を修正しました",
        "I44": "値を入力してください",
        "I45": "※{0}のノッチ情報を{1}ノッチまで戻します。\n",
        "I46": "を\n全部元に戻しますか？",
        "I47": "データを元に戻しました",
        "I48": "テキストで取り出しました",
        "I49": "車両情報を改造しました",
        "I50": "denファイルを上書きします\nそれでもよろしいでしょうか？\n(権限問題で上書き失敗することもあります)",
        "I51": "denファイルを上書きしました",
        "I52": "全車両同じ倍率で変更され、すぐ保存されます。\nそれでもよろしいですか？",
        "I53": "全車両同じ数値で変更され、すぐ保存されます。\nそれでもよろしいですか？",
        "I54": "全車両を改造しました",
        "I55": "編成数を修正しました",
        "I56": "カラー数を修正しました",
        "I57": "ノッチ情報を修正してください",
        "I58": "ノッチ情報を修正しますか？",
        "I59": "ノッチ数を変更しました",
        "I60": "この情報で修正しますか？",
        "I61": "情報を修正しました",
        "I62": "{0}の{1}番目を削除します。\nそれでもよろしいですか？",
        "I63": "モデル情報を修正しますか？",
        "I64": "モデル情報を修正しました",
        "I65": "lens情報数を修正しました",
        "I66": "lens情報を修正しました",
        "I67": "tail情報数を修正しました",
        "I68": "tail情報を修正しました",
        "I69": "BGM情報を修正しました",
        "I70": "このリストで修正しますか？",
        "I71": "この値で挿入しますか？",
        "I72": "車両数情報を修正しました",
        "I73": "ANIME数を修正しました",
        "I74": "ANIME情報を修正しました",
        "I75": "else1の情報を修正しました",
        "I76": "を修正しました",
        "I77": "駅名標数を修正しました",
        "I78": "駅名標情報を修正しました",
        "I79": "smf情報を修正しました",
        "I80": "リストを修正しました",
        "I81": "駅名位置情報を修正しました",
        "I82": "else2数を修正しました",
        "I83": "else2の情報を修正しました",
        "I84": "cpu情報を修正しました",
        "I85": "Comic Scriptを修正しました",
        "I86": "土讃線情報数を修正しました",
        "I87": "土讃線情報を修正しました",
        "I88": "レール情報を修正しました",
        "I89": "CSVで自動作成しました。\n(細かい分岐調整はCSVを修正する必要があります)",
        "I90": "RS移植ファイルを作成しました。",
        "I91": "{0}数を修正しました",
        "I92": "{0}情報を修正しました",
        "I93": "else4数を修正しました",
        "I94": "else4情報を修正しました",
        "I95": "AMB情報を修正しました",
        "I96": "レールCSVがあります。\n上書きしますか？\n(権限問題で上書き失敗することもあります)",
        "I97": "AMBのCSVがあります。\n上書きしますか？\n(権限問題で上書き失敗することもあります)",
        "I98": "レール{0}のメモリー情報を変更しますか？\nいいえを押すと変更をやめ、検索モードへ移行します。\n(権限問題で上書き失敗することもあります)",
        "I99": "レール{0}のメモリー情報を変更しました。",
        "I100": "AMB {0}のメモリー情報を変更しますか？\nいいえを押すと変更をやめ、検索モードへ移行します。\n(権限問題で上書き失敗することもあります)",
        "I101": "AMB {0}のメモリー情報を変更しました。",
        "I102": "このまま移してもよろしいですか？",
        "I103": "{0}を{1}の子に移します。\nこの要素の全ての子要素に影響が及びます。\n",
        "I104": "SMFを修正しました",
        "I105": "下記のモデルのみ出来ます",
        "I106": "{0}を読み込んでください",
        "I107": "モデルが違います",
        "I108": "標準軌を作成しました",
        "I109": "{0}を消します。\nこの要素の全ての子要素に影響が及びます。\nこのまま消してもよろしいですか？",
        "I110": "バイナリで取り出しました",
        "I111": "CSVで上書きした\n保存するボタンで【resources_new.assets】を作成します",
        "I112": "resources_new.assetsを作成しました。",
        "I113": "エクセルで取り出ししました。",
        "I114": "エクセルで上書きしました。",
        "I115": "レールNo.{0}に、重複するモデル名称\n「{1}」を使っています。\nこのままでよろしいですか？",
        "I116": "AMB No.{0}に、重複するモデル名称\n「{1}」を使っています。\nこのままでよろしいですか？",
        "I117": "エクセルのデータを読み込みしました。\n上書きしますか？",
        "I118": "コピー作業が終わりました",
        "I119": "タイプ情報を修正しますか？",
        "I120": "タイプ情報を修正しました",
        "I121": "x3dで抽出しました",
        "I122": "xで抽出しました"
    },
    "modify": "修正",
    "insert": "挿入",
    "delete": "削除",
    "error": "エラー",
    "intError": "整数エラー",
    "numberError": "数字エラー",
    "saveError": "保存エラー",
    "valueError": "値エラー",
    "readError": "読み込みエラー",
    "warning": "警告",
    "confirm": "確認",
    "success": "成功",
    "errorList": {
        "E1": "プログラムを選択してください",
        "E2": "定義されてないコマンド番号です({0})。読込を終了します。",
        "E3": "数字で入力してください。",
        "E4": "保存に失敗しました。\nファイルが他のプログラムによって開かれている\nまたは権限問題の可能性があります",
        "E5": "不正な値があります",
        "E6": "予想外のエラーが出ました。\n電車でDのコミックスクリプトではない、またはファイルが壊れた可能性があります。",
        "E7": "CSVで取り出す機能が失敗しました。\n権限問題の可能性があります。",
        "E8": "{0}行目のコマンド[{1}]は\n存在しないコマンドです",
        "E9": "{0}行目のコマンドに\n数字に変換できない要素[{1}]が入ってます",
        "E10": "重複してるFVT番号があります[ {0} ]",
        "E11": "{0}行に数字で変換できない要素があります",
        "E12": "{0}行のテキストをShift-jis変換できません",
        "E13": "ゲームを選択してください",
        "E14": "予想外のエラーです。",
        "E15": "{0}行のデータを読み込み失敗しました。",
        "E16": "ヘッダー一致しない",
        "E17": "smf名が空文字です",
        "E18": "予想外のエラーが出ました。\n電車でDのMDLINFOではない、またはファイルが壊れた可能性があります。",
        "E19": "予想外のエラーが出ました。\n電車でDのSMFではない、またはファイルが壊れた可能性があります。",
        "E20": "文字列の長さが長すぎです。",
        "E21": "予想外のエラーが出ました。\n電車でDのファイルではない、またはファイルが壊れた可能性があります。",
        "E22": "ノッチ情報を探せません",
        "E23": "{0}ノッチは非対応です",
        "E24": "ノッチのヘッダーがありません",
        "E25": "{0}ノッチ読み込み中\n{1}ノッチ情報読み込み失敗",
        "E26": "性能情報を探せません",
        "E27": "台車モデル情報を探せません",
        "E28": "編成数情報を探せません",
        "E29": "編成数が1個より少ないです",
        "E30": "車両モデル情報を探せません",
        "E31": "COLモデル情報を探せません",
        "E32": "パンタモデル情報を探せません",
        "E33": "パンタindex情報を探せません",
        "E34": "パンタindex情報が不正です",
        "E35": "パンタindex情報 読み込み失敗",
        "E36": "属性index情報を探せません",
        "E37": "レンズフレア情報を探せません",
        "E38": "テールランプ情報を探せません",
        "E39": "{0}行目の読み込み失敗",
        "E40": "編成数が2個より少ないです",
        "E41": "車両index情報を探せません",
        "E42": "車両index情報が不正です",
        "E43": "車両index情報 読み込み失敗",
        "E44": "モデルindex2情報を探せません",
        "E45": "カラー数情報を探せません",
        "E46": "カラー、モデル数情報を探せません",
        "E47": "台車モデルの数が2個より少ないです",
        "E48": "COL_index情報を探せません",
        "E49": "COL_index情報が不正です",
        "E50": "COL_index情報 読み込み失敗",
        "E51": "{0}の車両は存在しません",
        "E52": "{0}を探せません",
        "E53": "ノッチの行を読み込めません({0}行目)",
        "E54": "性能の行を読み込めません({0}行目)",
        "E55": "雨の性能の行を読み込めません({0}行目)",
        "E56": "カーブの性能の行を読み込めません({0}行目)",
        "E57": "その他の行を読み込めません({0}行目)",
        "E58": "振り子性能の行を読み込めません({0}行目)",
        "E59": "片輪走行の行を読み込めません({0}行目)",
        "E60": "整数で入力してください。",
        "E61": "{0}以上の整数で入力してください。",
        "E62": "コピー項目を選択してください",
        "E63": "CSVで取り出す機能が失敗しました。\n権限問題の可能性があります。",
        "E64": "テキストで取り出す機能が失敗しました。\n権限問題の可能性があります。",
        "E65": "LSはカラー数修正をサポートしません",
        "E66": "BSカラー修正はCSVで行ってください",
        "E67": "台車モデルは{0}個以上である必要があります",
        "E68": "選択したモデルは{0}両目で使ってます",
        "E69": "変更する機能はありません",
        "E70": "存在しないレールです",
        "E71": "CSVで上書きが失敗しました。\n権限問題の可能性があります。",
        "E72": "RS移植ファイル作成失敗しました。\n権限問題の可能性があります。",
        "E73": "存在しないAMBです",
        "E74": "読み込み失敗しました。",
        "E75": "最終行目に子データがありません",
        "E76": "{0}のレールデータではありません",
        "E77": "ゲームを見つけられませんでした。",
        "E78": "ゲームのメモリーを参照できません\n管理者権限で実行してください",
        "E79": "レールのメモリーを参照できません。\nステージを選択してから実行してください",
        "E80": "保存失敗しました。レールのメモリーを参照できません。",
        "E81": "AMBのメモリーを参照できません。\nステージを選択してから実行してください",
        "E82": "保存失敗しました。AMBのメモリーを参照できません。",
        "E83": "bodyClass index情報が不正です",
        "E84": "bodyモデル index情報が不正です",
        "E85": "pantaモデル index情報が不正です",
        "E86": "bodyClassのindexの数が編成数と不一致です",
        "E87": "bodyモデルのindexの数が編成数と不一致です",
        "E88": "pantaモデルのindexの数が編成数と不一致です",
        "E89": "バイナリで取り出す機能が失敗しました。\n権限問題の可能性があります。",
        "E90": "AudioClipはサポートしていません",
        "E91": "UnityPyがインストールされていません。\nsetup.batでインストールしてください",
        "E92": "{0}行目読み込みエラー！\nElse3の子データが、数と一致しません",
        "E93": "リストは{0}個以上である必要があります",
        "E94": "エクセルで取り出す機能が失敗しました。\n権限問題の可能性があります。",
        "E95": "シート名「{0}」が存在しません。",
        "E96": "No.{0}のモデル「{1}」は存在しません",
        "E97": "レールNo.{0}の要素４の要素がありません",
        "E98": "形式が合わないテキストファイルです。\n{0}",
        "E99": "「BGM、配置情報」シートで、レールデータのバージョンなし",
        "E100": "「{0}」シートで、{1}のラベルなし",
        "E101": "「{0}」シートで、{1}行目の読込エラー",
        "E102": "レールデータの上書きを中止します。",
        "E103": "エクセルのファイルが存在しません：",
        "E104": "denファイルが存在しません：",
        "E105": "denファイルがstagedataではありません：",
        "E106": "stagedataで「{0}」がありません",
        "E107": "エクセルで「{0}」がありません",
        "E108": "エクセルの「{0}」の読込エラー",
        "E109": "レールデータのモデル名「{0}」は存在しません",
        "E110": "AMBデータのモデル名「{0}」は存在しません",
        "E111": "エクセルの「{0}」の読込中、「{1}」のデータが空白です",
        "E112": "stagedataの「{0}」の設定データ数({1})は\n実のデータ数({2})より多いです",
        "E113": "No.{0}の【AMB個数データ】が0以下です",
        "E114": "stagedataの「{0}」の読込エラー\n(No.{1}のデータ＝【{2}】)",
        "E115": "train_org_dataが古いバージョンです",
        "E116": "「{0}」の個数(データ)がありません",
        "E117": "「{0}」の個数(データ)が異常です\n(データ＝【{1}】)",
        "E118": "stagedataにいくつかエラーがありました。\n詳しくはstageError.log、stageWarning.logを確認ください",
        "E119": "AMBのNo.{0}で使われてないAMB情報があります",
        "E120": "AMBのNo.{0}で【{1}】は、AMBとして使えないモデルです",
        "E121": "レールのNo.{0}で【{1}】は、レールとして使えないモデルです",
        "E122": "レールのNo.{0}で【{1}】は{2}ですが、{3}で指定しています",
    },
    "excel": {
        "errorColor": "FF0000",
        "warningColor": "FFFF00",
        "disableColor": "CCCCCC"
    },
    "menu": {
        "program": {
            "name": "改造プログラム",
            "SSUnity": "SS改造",
            "orgInfoEditor": "車両性能",
            "mdlBin": "モデルバイナリ",
            "mdlinfo": "MDLINFO",
            "comicscript": "コミックスクリプト",
            "musicEditor": "BGMリスト",
            "fvtMaker": "FVT作成",
            "railEditor": "レールエディター",
            "rsRail": "RSのレール・AMB",
            "smf": "SMF",
            "exit": "終了",
        },
        "file": {
            "name": "ファイル",
            "loadFile": "ファイルを開く",
        },
        "csv": {
            "name": "CSVオプション",
            "rail": {
                "opt1": "レールCSVを常に確認",
                "opt2": "レールCSVを常に上書きする",
                "opt3": "レールCSVを上書きしない",
            },
            "amb": {
                "opt1": "AMBのCSVを常に確認",
                "opt2": "AMBのCSVを常に上書きする",
                "opt3": "AMBのCSVを上書きしない",
            }
        },
        "comicscript": {
            "gameList": ["SS", "RS", "CS", "BS", "LS"],
            "name": "スクリプトを読込むゲーム"
        },
        "smf": {
            "name": "SMF書込みオプション",
            "write": {
                "opt1": "FRMを書込む",
                "opt2": "MESHを書込む",
                "opt3": "MESHの詳しい箇所まで書込む",
                "opt4": "MTRLを書込む",
            }
        },
        "SSUnity": {
            "name": "xlsx読込み・書込みオプション",
            "write": {
                "model1": "モデルを名称で出力",
                "model2": "モデルをindexで出力",
                "flag1": "フラグを10進数",
                "flag2": "フラグを16進数",
                "ambRead1": "AMB情報を改行",
                "ambRead2": "AMB情報を１行",
            }
        },
        "appearance": {
            "rootFrame": "外観設定",
        }
    },
    "appearance": {
        "updateConfirm": "この設定で変更しますか？",
        "success": "設定した色で変更しました",
        "rootFrame": {
            "editRootFrameTitle": "外観の変更",
            "windowsDialogLabel": "Windowsのダイアログ",
            "lightModeRadioLabel": "ライトモード",
            "darkModeRadioLabel": "ダークモード",
            "tkThemeNameLabel": "テーマ",
            "rootFrameLabel": "メイン",
            "bgColorLabel": "背景色",
            "fgColorLabel": "文字色",
            "labelLabel": "ラベル",
            "labelFrameLabel": "ラベルフレーム",
            "radiobuttonLabel": "ラジオボタン",
            "treeviewLabel": "テーブルのアイテム",
            "selectedBgColorLabel": "選択時\n背景色",
            "selectedFgColorLabel": "選択時\n文字色",
            "colorEditButtonLabel": "色を変える",
            "colorDefaultButtonLabel": "デフォルト色にする",
            "askColorSetDefault": "デフォルト色の設定しますか？",
            "buttonLabel": "ボタン(※背景色はテーマ依存)",
            "entryLabel": "入力欄(※背景色はテーマ依存)",
            "treeviewThemeLabel": "テーブル(※テーマ依存要素)",
            "treeviewFieldBgLabel": "外側の\n背景色",
            "treeviewHeaderBgLabel": "ヘッダーの\n背景色",
            "treeviewHeaderFgLabel": "ヘッダーの\n文字色",
            "comboboxLabel": "コンボボックス(※テーマ依存)\nプルダウンは再起動後、適用されます",
            "radioThemeLabel": "ラジオボタン(※テーマ依存)",
            "radioButtonColorLabel": "ボタンの色",
            "radioButtonSelColorLabel": "選択時\nボタンの色",
        }
    },
    "update": {
        "title": "バージョン(1回のみの確認)",
        "message": "最新バージョン {0}があります。\nダウンロードページを開きますか？"
    },
    "app": {
        "title": "電車でD 改造 統合版 {0}"
    }
}
